### ISSUE TITLE
v0.10 download disc image has bug in /Examples/AppleScript/Pashua.scpt

### ISSUE THREAD

**Issue by mklement0** [BlueM/Pashua-Binding-AppleScript#1]
Line

`return (path to applications folder from system domain as text) & "Pashua.app"`

should be

`return (path to applications folder from system domain as text) & "Pashua.app:"`

Note that this has already been fixed in the repo here, but affects the download from http://www.bluem.net/en/mac/pashua/ as of 27 Feb 2015.

Great tool, btw - thank you for making it freely available.
Can I suggest making the documentation available online as well? Unless I'm overlooking something, it seems that it's only included in the download (as an HTML file).

**Comment by BlueM** [comment]
Fixed the code in the DMG. Thanks for the info.
